### ISSUE TITLE
Sikuli-api whether support window xp os in future?

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#15]
_Original author: songbing...@126.com (January 08, 2013 07:15:12)_
1. I write the script on win7 os and work well.
2. But I migrate the script to window xp os, and I met these execption.
   java.lang.reflect.InvocationTargetException(C:\Documents and Settings\Administrator\Local Settings\Temp\javacpp4444462470727\jniopencv_core.dll: Can't find dependent libraries

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=15_

**Comment by doubleshow** [comment]
_From miglecz on January 09, 2013 19:26:39_
I am running sikuli on win xp. Works perfectly.

**Comment by doubleshow** [comment]
_From songbing...@126.com on January 11, 2013 08:07:45_
Hi miglecz,

I use sikuli-api-1.0.2-standalone.jar jar in my project, there are my code:

public ScreenRegion findImage(String address) {
    ImageTarget target = new ImageTarget(new File(address));
    ScreenRegion sr = new DesktopScreenRegion();
    return sr.find(target);
}

public void clickImage(String address) {
    mouse.click(findImage(address).getCenter());
}

When I execute the clickImage api, I met these error infos:
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.micro.tests.CaseTemplate.executeKeyword(CaseTemplate.java:277)
    at com.micro.tests.CaseTemplate.clickImage(CaseTemplate.java:1080)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\song.bing\AppData\Local\Temp\javacpp1835117248908963\jniopencv_core.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1807)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1703)
    at java.lang.Runtime.load0(Runtime.java:770)
    at java.lang.System.load(System.java:1003)
    at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:418)
    at com.googlecode.javacpp.Loader.load(Loader.java:368)
    at com.googlecode.javacpp.Loader.load(Loader.java:315)
    at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:131)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.googlecode.javacpp.Loader.load(Loader.java:334)
    at com.googlecode.javacpp.Loader.load(Loader.java:315)
    at com.googlecode.javacv.cpp.opencv_core$CvArr.<clinit>(opencv_core.java:158)
    at org.sikuli.core.cv.ImagePreprocessor.createGrayscale(ImagePreprocessor.java:52)
    at org.sikuli.core.search.algorithm.TemplateMatcher.findMatchesByGrayscaleAtOriginalResolution(TemplateMatcher.java:18)
    at org.sikuli.api.ImageTarget.getUnordredMatches(ImageTarget.java:122)
    at org.sikuli.api.DefaultTarget.doFindAll(DefaultTarget.java:93)
    at org.sikuli.api.DefaultScreenRegion._find(DefaultScreenRegion.java:73)
    at org.sikuli.api.DefaultScreenRegion.find(DefaultScreenRegion.java:64)
    at com.micro.tests.keywords.sikuli.impl.SikuliKeywordImpl.findImage(SikuliKeywordImpl.java:31)
    at com.micro.tests.keywords.sikuli.impl.SikuliKeywordImpl.clickImage(SikuliKeywordImpl.java:69)
    ... 8 more

If my miss some dependent libs? or other issue?

Best Regards!
-Micro

**Comment by doubleshow** [comment]
_From miglecz on January 11, 2013 13:57:40_
Try rebuilding your project under winXp with java 1.6.

**Comment by doubleshow** [comment]
_From mbdiwa...@gmail.com on January 19, 2013 00:55:28_
I am facing the exact issue, compile on Windows 7 and, execute on Win XP 

C:\Documents and Settings\hudson\Local Settings\Temp\javacpp225377380582771\jniopencv_core.dll: Can't find dependent libraries

**Comment by doubleshow** [comment]
_From writwiks...@gmail.com on April 02, 2013 10:24:14_
Try to install Microsoft Visual C + + 2010 Redistributable Package(http://www.microsoft.com/en-us/download/details.aspx?id=5555) on your computer
