### ISSUE TITLE
NullPointerException when doing findAll

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#18]
_Original author: miglecz (January 17, 2013 21:38:12)_

Stacktrace:

java.lang.NullPointerException
at java.awt.image.ColorConvertOp.filter(Unknown Source)
at org.sikuli.core.cv.ImagePreprocessor.createGrayscale(ImagePreprocessor.java:51)
at org.sikuli.core.search.algorithm.TemplateMatcher.findMatchesByGrayscaleAtOriginalResolution(TemplateMatcher.java:18)
at org.sikuli.api.ImageTarget.getUnordredMatches(ImageTarget.java:122)
at org.sikuli.api.DefaultTarget.doFindAll(DefaultTarget.java:93)
at org.sikuli.api.MultiStateTarget.getUnordredMatches(MultiStateTarget.java:27)
at org.sikuli.api.DefaultTarget.doFindAll(DefaultTarget.java:93)
at org.sikuli.api.DefaultScreenRegion.findAll(DefaultScreenRegion.java:58)
...
ScreenRegion region = ...;
region.findAll(new ImageTarget(ImageIO.read(new File(&quot;img.png&quot;))));

What is this, why is this?

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=18_

**Comment by doubleshow** [comment]
_From miglecz on January 17, 2013 21:44:03_
Image attached. Made with mspaint.

**Comment by doubleshow** [comment]
_From doubles...@gmail.com on January 17, 2013 21:44:30_
can you try other images? do you experience the same problem? Or only with this lockedtargetbottom image?
