### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#22]
_Original author: deb...@gmail.com (January 23, 2013 11:53:45)_

<b>What steps will reproduce the problem?</b>
1. Run the attached maven project

What is the expected output? Something
What do you see instead? Nothing

The output is 

SLF4J: Failed to load class &quot;org.slf4j.impl.StaticLoggerBinder&quot;.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread &quot;main&quot; java.lang.NullPointerException
        at org.sikuli.api.visual.Canvas.addLabel(Canvas.java:230)
        at tk.ganian.sikuli.template.main(template.java:35)

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=22_

**Comment by doubleshow** [comment]
_From lasyaku...@gmail.com on January 23, 2013 22:48:04_
May be you failed to create an instance of some class in your project. Usually that is the reason for null pointer exception.

**Comment by doubleshow** [comment]
_From miglecz on January 24, 2013 11:37:50_
Line 31 returns a null ScreenRegion because the target is not appearing in 5 seconds on screen.
Calling canvas.addLabel(null... causes a NullPointerException.
