### ISSUE TITLE
Can't find dependent libraries AppData\Local\Temp\javacpp173971675343433\jniopencv_core.dll

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#25]
_Original author: mbdiwa...@gmail.com (January 25, 2013 00:06:48)_

<b>What steps will reproduce the problem?</b>
1. Running the following code on 32 bit jvm
        DesktopCanvas canvas = new DesktopCanvas();
        ScreenRegion sr = new DesktopScreenRegion();
        Target image2 = new ImageTarget(new File(&quot;C:\path\to\image\file.png&quot;));

```
   ScreenRegion fr = //sr;
    sr.find(image2);
```

<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
ImageTarget should be found

<b>What version of the product are you using? On what operating system?</b>
a) sikuli-api-1.0.2-standalone.jar
b) &quot;c:\Program Files (x86)\Java\jre6\bin\java.exe&quot; -version
java version &quot;1.6.0_31&quot;
Java(TM) SE Runtime Environment (build 1.6.0_31-b05)
Java HotSpot(TM) Client VM (build 20.6-b01, mixed mode, sharing)

3) Windows 7 professional 64 bit
4) RAM 8 gb
5) AMD Phenom II X4 B95 Processor

<b>Please provide any additional information below.</b>
# Exception in logs:

AppData\Local\Temp\javacpp173971675343433\jniopencv_core.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(Unknown Source)
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.load0(Unknown Source)
    at java.lang.System.load(Unknown Source)
    at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:418)
    at com.googlecode.javacpp.Loader.load(Loader.java:368)
    at com.googlecode.javacpp.Loader.load(Loader.java:315)
    at com.googlecode.javacv.cpp.opencv_core.&lt;clinit&gt;(opencv_core.java:131)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.googlecode.javacpp.Loader.load(Loader.java:334)
    at com.googlecode.javacpp.Loader.load(Loader.java:315)
    at com.googlecode.javacv.cpp.opencv_core$CvArr.&lt;clinit&gt;(opencv_core.java:158)
    at org.sikuli.core.cv.ImagePreprocessor.createGrayscale(ImagePreprocessor.java:52)
    at org.sikuli.core.search.algorithm.TemplateMatcher.findMatchesByGrayscaleAtOriginalResolution(TemplateMatcher.java:18)
    at org.sikuli.api.ImageTarget.getUnordredMatches(ImageTarget.java:122)
    at org.sikuli.api.DefaultTarget.doFindAll(DefaultTarget.java:93)
    at org.sikuli.api.DefaultScreenRegion._find(DefaultScreenRegion.java:73)
    at org.sikuli.api.DefaultScreenRegion.find(DefaultScreenRegion.java:64)
    at 

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=25_

**Comment by doubleshow** [comment]
_From writwiks...@gmail.com on February 14, 2013 08:07:18_
I am also faced similar issue in XP.

**Comment by doubleshow** [comment]
_From AndrewEF...@gmail.com on February 24, 2013 12:38:46_
Also experienced this with Windows 7 32bit

**Comment by doubleshow** [comment]
_From gusev....@gmail.com on March 01, 2013 07:12:20_
To fix must be installed on your computer Microsoft Visual C + + 2010 Redistributable Package(http://www.microsoft.com/en-us/download/details.aspx?id=5555)

**Comment by doubleshow** [comment]
_From writwiks...@gmail.com on March 06, 2013 13:26:52_
Working after installing Microsoft Visual C + + 2010 Redistributable Package

**Comment by doubleshow** [comment]
_From mbdiwa...@gmail.com on March 21, 2013 00:18:37_
Its working as per #  3, we can close this issue

**Comment by horuktaras** [comment]
Does not work on WIN10.

**Comment by aymann** [comment]
yea it does not work on win10

**Comment by evgmoskalenko** [comment]
Does not work on MacOS ElCapitan 10.11.6
