### ISSUE TITLE
Mouse assumes ScreenLocation.getScreen will be a DesktopScreen, but that's not true here

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#4]
_Original author: jasonpar...@gmail.com (October 25, 2012 17:54:06)_

Here's a snippet of code where the resulting Screen is an anonymous inner class from ScreenRegion.snapshot:

(This is written in Xtend)

```
    var s = new ScreenRegion
    var m = new Mouse
    m.click(s.find(new TextTarget('HelloWorldExample.java')).center)
```

Results in:

Exception in thread &quot;main&quot; java.lang.ClassCastException: org.sikuli.api.ScreenRegion$1 cannot be cast to org.sikuli.api.robot.DesktopScreen
    at org.sikuli.api.robot.Desktop.getMouse(Desktop.java:111)
    at org.sikuli.api.robot.Mouse.getDesktopMouse(Mouse.java:14)
    at org.sikuli.api.robot.Mouse.click(Mouse.java:38)
    at com.dingrocket.e2e.WebTests.run(WebTests.java:22)
    at com.dingrocket.e2e.WebTests.main(WebTests.java:39)

My workaround is to create a new ScreenLocation with the existing one's x and y but the proper DesktopScreen instance

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=4_

**Comment by doubleshow** [comment]
_From doubles...@gmail.com on October 28, 2012 13:28:58_
Thank you for reporting this bug!
