### ISSUE TITLE
java.lang.NumberFormatException  being thrown when running sikuli slides - (copy and paste screenshot bug)

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#40]
_Original author: ciceroau...@gmail.com (March 28, 2013 17:11:25)_

<b>What steps will reproduce the problem?</b>
1.Downloaded sikuli-slides
2.Open cmd window
3.Typed java -jar sikuli-slides-1.0.0.jar sikuli.pptx

<b>What is the expected output? What do you see instead?</b>
I was expecting sikuli to at least find the images in the screen
I got this message:
Exception in thread &quot;main&quot; java.lang.NumberFormatException: null
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at org.sikuli.slides.parsing.SlideParser.startElement(SlideParser.java:113)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at javax.xml.parsers.SAXParser.parse(Unknown Source)
at javax.xml.parsers.SAXParser.parse(Unknown Source)
at org.sikuli.slides.parsing.SlideParser.parseDocument(SlideParser.java:59)
at org.sikuli.slides.core.SikuliPowerPoint.parseSlideFile(SikuliPowerPoint.java:85)
at org.sikuli.slides.core.SikuliPowerPoint.runSikuliPowerPoint(SikuliPowerPoint.java:48)
at org.sikuli.slides.guis.MainUI.doSikuliPowerPoint(MainUI.java:33)
at org.sikuli.slides.guis.MainUI.main(MainUI.java:43)

<b>What version of the product are you using? On what operating system?</b>
sikuli-slides version 1.0.0. I am using Windows 7 64-bit and create the .pptx file using Microsoft Office Powerpoint 2007.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=40_

**Comment by doubleshow** [comment]
_From khalid3ahmed on March 30, 2013 00:25:58_
@ciceroaugusto Thank you for reporting this bug and attaching the .pptx file. This is a known bug that occurs when you copy and paste the screenshot into the slide. The workaround is to insert the screenshot into the slide or insert a duplicate slide instead of copying and pasting the screenshot. This bug is being investigated. Thanks!

**Comment by doubleshow** [comment]
_From khalid3ahmed on April 09, 2013 03:40:41_
Fixed in sikuli-slides 1.1.0
