### ISSUE TITLE
"No X11 DISPLAY variable was set" error came on Linux using Sikuli Stand Alone api 

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#41]
_Original author: dharmesh...@gmail.com (March 30, 2013 16:19:18)_

<b>What steps will reproduce the problem?</b>
1. I Created a sample script like one below on my GNU/Linux machine using the Eclipse IDE. I added the sikuli standalone .jar.

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.swing.plaf.basic.BasicSplitPaneUI.KeyboardEndHandler;

import org.sikuli.api.*;
import org.sikuli.api.robot.Keyboard;
import org.sikuli.api.robot.Mouse;
import org.sikuli.api.robot.desktop.DesktopKeyboard;
import org.sikuli.api.robot.desktop.DesktopMouse;
import org.sikuli.api.visual.Canvas;
import org.sikuli.api.visual.DesktopCanvas;

import static org.sikuli.api.API.*;

public class FirstStandAlone 
{

```
    public static void main(String[] args) throws MalformedURLException, InterruptedException 
    {           

            // Open the main page of Google Code in the default web browser
            browse(new URL(&quot;MYAPP&quot;));


            // Create a screen region object that corresponds to the default monitor in full screen 
            ScreenRegion s = new DesktopScreenRegion();
            System.out.println(&quot;jiuiuiuddfcscdesi&quot;);

            ScreenRegion result = s.wait(new ImageTarget(new File(&quot;//home//dgangwar/LoginFields.PNG&quot;)), 5000);
    System.out.println(null==result);
    System.out.println(&quot;jiuiuiui&quot;);
```

//              //Target imageTarget = new ImageTarget(new File(DataFile.USERIDTEXT));
                Mouse mouse = new DesktopMouse();
                mouse.click(result.getCenter());

```
    Mouse mouse = new DesktopMouse();
            mouse.click(result.getCenter());
            Keyboard kb = new DesktopKeyboard();
            kb.type(&quot;Hijhiih&quot;);

    }
```

}
1. After running this program I got the below error.
   
   ```
   sikuli main&quot; java.lang.UnsatisfiedLinkError:
   ```
2. I added the Path and Sikuli_Home variable to my Eclipse Run configuration, after this the above error did not come.
3. Now I ran the Test case and got the below error. I have set up my VNC with 3 screen resolutions.
   
   Exception in thread &quot;main&quot; java.awt.HeadlessException: 
   No X11 DISPLAY variable was set, but this program performed an operation which requires it.
   at java.awt.Desktop.getDesktop(Desktop.java:142)
   at org.sikuli.api.API.browse(API.java:20)
   at FirstStandAlone.main(FirstStandAlone.java:18)

<b>What is the expected output? What do you see instead?</b>

```
I used the same code on windows and it worked fine but on Linux I had the above problem.
```

<b>What version of the product are you using? On what operating system?</b>

```
GNU/LINUX , Sikuli-api-1.0.2-standalone.jar, Java SE 6
```

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=41_

**Comment by vinogradoff** [comment]
Have you tried to set DISPLAY variable?

```
export DISPLAY=localhost:0
```
