### ISSUE TITLE
Can't get the simple HelloWorldExample example working

### ISSUE THREAD

**Issue by doubleshow** [sikuli/sikuli-api#9]
_Original author: marton...@gmail.com (November 30, 2012 11:18:15)_

I can't get the hello world example to work.
The following line returns a null value:
ScreenRegion r = s.wait(imageTarget, 5000);

I downloaded two dependencies manually because java complained about missing slf4 and log4j. Why aren't theses mentioned in the dependencies?

---
## ---- What steps will reproduce the problem? ----
1. Run the Quick start code
2. Wait for the browser to open webpage
3. wait for another 5 sec for s.wait(imageTarget, 5000);
4. Se the NullPointerException in the log

--- What is the expected output? ---
Displaying &quot;Hello World&quot; next to the target and then clicking on it.

---
## ----What do you see instead? ----

Output:

r: null
Exception in thread &quot;main&quot; java.lang.NullPointerException
    at org.sikuli.api.visual.Canvas.addLabel(Canvas.java:230)
    at HelloWorldExample.main(HelloWorldExample.java:37)

---
## --- What version of the product are you using? On what operating system?

windows 7 64bit
jdk6 64-bit
sikuli-api-1.0.2-standalone.jar

---
## -- Please provide any additional information below. --

I am using the following code. The complete Eclipse project: http://ge.tt/7HBAtdS/v/0?c

---
## --- Code 

import java.net.MalformedURLException;
import java.net.URL;

import org.sikuli.api.API;
import org.sikuli.api.DesktopScreenRegion;
import org.sikuli.api.ImageTarget;
import org.sikuli.api.ScreenRegion;
import org.sikuli.api.Target;
import org.sikuli.api.robot.Mouse;
import org.sikuli.api.robot.desktop.DesktopMouse;
import org.sikuli.api.visual.Canvas;
import org.sikuli.api.visual.DesktopCanvas;

public class HelloWorldExample {

```
public static void main(String[] args) throws MalformedURLException {

    // Open the main page of Google Code in the default web browser
    API.browse(new URL(&quot;http://code.google.com&quot;));

    // Create a screen region object that corresponds to the default monitor
    // in full screen
    ScreenRegion s = new DesktopScreenRegion();

    // Specify an image as the target to find on the screen
    URL imageURL = new URL(&quot;http://code.google.com/images/code_logo.gif&quot;);
    Target imageTarget = new ImageTarget(imageURL);

    // Wait for the target to become visible on the screen for at most 5 seconds
    // Once the target is visible, it returns a screen region object corresponding
    // to the region occupied by this target
    ScreenRegion r = s.wait(imageTarget, 5000);

    // Display &quot;Hello World&quot; next to the found target for 3 seconds
    Canvas canvas = new DesktopCanvas();
    System.out.println(&quot;r: &quot; + r); 
    canvas.addLabel(r, &quot;Hello World&quot;).display(3);

    // Click the center of the found target
    Mouse mouse = new DesktopMouse();
    mouse.click(r.getCenter());
}
```
## }

_Original issue: http://code.google.com/p/sikuli-api/issues/detail?id=9_

**Comment by doubleshow** [comment]
_From anup....@gmail.com on December 05, 2012 06:08:18_
I am also facing the same issue , I got the SLF4J issue resolved by adding the corresponding JAR . But not able to get the Null Pointer cleared . I have tried adding s.find also yet to no avail.

**Comment by doubleshow** [comment]
_From doubles...@gmail.com on December 07, 2012 11:11:22_
null pointer means Sikuli isn't able to see the image on the screen. 
can you please provide a screenshot of the screen when Sikuli is trying to find the logo of google code? 
Thanks!

**Comment by doubleshow** [comment]
_From marton...@gmail.com on December 07, 2012 11:23:56_
Screenshot of my entire desktop. It is taken when I am using a dual screen setup.

**Comment by doubleshow** [comment]
_From doubles...@gmail.com on December 07, 2012 19:32:14_
can you try two things?
1. Test with a single monitor configuration.
2. Try
ScreenRegion s = new DesktopScreenRegion();
s.setScreen(new DesktopScreen(1));

please let us know whether if either (or both) solutions work

**Comment by doubleshow** [comment]
_From marton...@gmail.com on December 07, 2012 20:06:15_
OMG!
I am so sorry! Both at home and work I had a browser zoom-level set at something other then 100&#37; That is why it did not find anything >_<

The code from my first post works as it should when the browser zoom-level is set to 100&#37;. The Hello world is showing up and the mouse is clicking on the logo.

Thank you for the support! And I apologize again for searching for somehting that was not broken.

Now I can start playing with this API :)

**Comment by doubleshow** [comment]
_From roopapat...@gmail.com on March 23, 2013 06:00:35_
Even I can't get the hello world example to work.
I followed the same steps. I am getting error

Exception in thread "main" org.sikuli.api.SikuliRuntimeException: Image file can not be loaded from http://code.google.com/images/code_logo.gif because Can't get input stream from URL!
    at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:46)
    at HelloWorldExample.main(HelloWorldExample.java:25)

**Comment by doubleshow** [comment]
_From marton...@gmail.com on March 23, 2013 13:54:07_
It sounds like a network connection issue. My test code in the first post is still working for me.
Are you behind a proxy? Slow internet connection? etc.

## Try this code snippet to test if it is a network issue.

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
public static void main(String[] args) {
    try {
        URL imageURL = new URL("http://code.google.com/images/code_logo.gif");
        Object ob = imageURL.getContent();
        System.out.println("This object should be an image class of some sort: " + ob);
    } catch (MalformedURLException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }

## }

I get the following output:
"This object should be an image class of some sort: sun.awt.image.URLImageSource@587bd9f2"

**Comment by doubleshow** [comment]
_From roopapat...@gmail.com on March 24, 2013 16:03:52_
Thank you.. now its working for me tooo!!!!!!!!1111
